### ISSUE TITLE
Should `snow -- ice` be `snow <--> ice` ? 

### ISSUE THREAD

**Issue by mankoff** [NASA-GISS/freshwater-forcing-workshop#14]
In the coupled Type 1 and Type 2 models at https://github.com/NASA-GISS/freshwater-forcing-workshop/blob/main/freshwater.org or in the original PDF linked there,

Should there be arrows between snow and ice? I believe so. For example, if the atmosphere melts enough snow, some snow models pull from the ice layer below.

https://github.com/NASA-GISS/freshwater-forcing-workshop/blob/5888462692dcd698ea6226396ed11e8d27356e15/freshwater.org?plain=1#L136-L140

@dringeis

**Comment by dringeis** [comment]
Yes I agree, in the coupled case, there should be a bi-directionnal arrow.
